### ISSUE TITLE
How to set a group link?

### ISSUE THREAD

**Issue by sigint93** [RememberTheAir/GroupButler#10]
I don't understand how to use accurately the "/setlink" command. What should I type next to it in order to set a link for the group?

**Comment by RememberTheAir** [comment]
@sigint93 You have to type the group link after "/link"

I find it useful because a lot of times, the group link is needed but the owner is not online. So moderators can retrieve it by typing "/link"

**Comment by sigint93** [comment]
Thanks, so a "owner", that isn't the real creator of the group, can't create a new link?

**Comment by RememberTheAir** [comment]
@sigint93 Yes axactly

**Comment by BH-YAGHI** [comment]
@RememberTheAir  cheek /bc command its dont work !

**Comment by RememberTheAir** [comment]
@BH-YAGHI It is working for me. Check your markdown
