### ISSUE TITLE
Italiano translation

### ISSUE THREAD

**Issue by Mistero5050** [RememberTheAir/GroupButler#108]
This media is forbidden" message should be translated 
"Questo tipo di media non è consentito in questo gruppo." in italian and not this (currently): "Questo tipo di media non Ã¨ consentito in questo gruppo."

The problem is "è" character

**Comment by RememberTheAir** [comment]
Non ti preoccupare, sono italiano :)
Purtroppo sono senza wifi a casa da ormai una settimana (grazie, telecom) e non ho la possibilità di aggiornare il bot. Come puoi vedere dal file con le stringhe in italiano, l'errore è già stato corretto
