### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by Santagain** [RememberTheAir/GroupButler#109]
Hello, I change the line to pt_br but the bot don't start on pt_BR only in english

*languages.lua:62*
`locale.language = 'pt_BR' -- default language`

**Comment by RememberTheAir** [comment]
Check if the message that the bot is supposed to send is marked as "fuzzy" in the translation file. 
Strings marked as fuzzy are not used if "allow_fuzzy_translations" in config.lua is set on false

**Comment by Santagain** [comment]
even marking this as true does not work, already tried with true and false

**Comment by RememberTheAir** [comment]
Just checked, you have to change the following line:

_bot.lua: 152_
`locale.language = db:get('lang:'..msg.chat.id) or 'en' --group language`

Where `'en'` is the default language if the group/user doesn't have a personal language set

**Comment by Santagain** [comment]
fine, it's working now!
