### ISSUE TITLE
rapporteer 'n probleem :(

### ISSUE THREAD

**Issue by Africa-bamBOo** [RememberTheAir/GroupButler#117]
hallo my vriend.
When add robot in the new group, bot does not welcoming to new member!
GroupButler welcoming to my old group but in new group does not welcoming
(in /config welcome is on but....)

**Sterkte!**

**Comment by SaeedRahmani66** [comment]
Hello
Are you using bot in normal group?
and which bot you are using?

**Comment by Africa-bamBOo** [comment]
no my groupo is super,
@GroupButler_bot

**Comment by SaeedRahmani66** [comment]
i tested it and worked fine. please disable and then enable the welcome message again or use @GBReborn_bot

**Comment by Africa-bamBOo** [comment]
ok thank you.
