### ISSUE TITLE
I have problem with start launch.sh

### ISSUE THREAD

**Issue by riyanloeqman** [RememberTheAir/GroupButler#152]
lua: bot.lua:2: module 'socket.url' not found:
	no field package.preload['socket.url']
	no file '/usr/local/share/lua/5.2/socket/url.lua'
	no file '/usr/local/share/lua/5.2/socket/url/init.lua'
	no file '/usr/local/lib/lua/5.2/socket/url.lua'
	no file '/usr/local/lib/lua/5.2/socket/url/init.lua'
	no file '/usr/share/lua/5.2/socket/url.lua'
	no file '/usr/share/lua/5.2/socket/url/init.lua'
	no file './socket/url.lua'
	no file '/usr/local/lib/lua/5.2/socket/url.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/socket/url.so'
	no file '/usr/lib/lua/5.2/socket/url.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './socket/url.so'
	no file '/usr/local/lib/lua/5.2/socket.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/socket.so'
	no file '/usr/lib/lua/5.2/socket.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './socket.so'
stack traceback:
	[C]: in function 'require'
	bot.lua:2: in main chunk
	[C]: in ?

can you help me? sorry i beginner programmer :(

**Comment by RememberTheAir** [comment]
You are missing the `luasocket` module.
I have forgot to delete a line of code in `bot.lua`, thanks for the report.

You have two way to fix this:
- delete the following line from `bot.lua`: [*line 21*](https://github.com/RememberTheAir/GroupButler/blob/master/bot.lua#L21) if you are using the `master` branch or [*line 19*](https://github.com/RememberTheAir/GroupButler/blob/beta/bot.lua#L19) if you are using the `beta` branch
- install `lua-socket` module with `sudo luarocks install luasocket`

**Comment by riyanloeqman** [comment]
@RememberTheAir thank you
