### ISSUE TITLE
no file error

### ISSUE THREAD

**Issue by TME97** [RememberTheAir/GroupButler#162]
Could someone help me to fix the error?

        no file '/usr/local/share/lua/5.2/socket/url.lua'
        no file '/usr/local/share/lua/5.2/socket/url/init.lua'
        no file '/usr/local/lib/lua/5.2/socket/url.lua'
        no file '/usr/local/lib/lua/5.2/socket/url/init.lua'
        no file '/usr/share/lua/5.2/socket/url.lua'
        no file '/usr/share/lua/5.2/socket/url/init.lua'
        no file './socket/url.lua'
        no file '/usr/local/lib/lua/5.2/socket/url.so'
        no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/socket/url.so'
        no file '/usr/lib/lua/5.2/socket/url.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './socket/url.so'
        no file '/usr/local/lib/lua/5.2/socket.so'
        no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/socket.so'
        no file '/usr/lib/lua/5.2/socket.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './socket.so'

**Comment by mymedia2** [comment]
Make sure that you have installed the luasocket module from luarocks.
Use the installation script from the `master` branch.

**Comment by TME97** [comment]
ok i#ll try it thank you

**Comment by TME97** [comment]
@mymedia2 i tried but same error
