### ISSUE TITLE
Bot dont responding to any message

### ISSUE THREAD

**Issue by TME97** [RememberTheAir/GroupButler#163]
BOT RUNNING:	[@PokeButlerBot] [PokeButler] [320927667]
but dont responding... any idea?

**Comment by SaeedRahmani66** [comment]
**Make sure privacy is disabled** (more info can be found by heading to the [official Bots FAQ page](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get)). Send `/setprivacy` to [@BotFather](http://telegram.me/BotFather) to check the current status of this setting.

**Comment by RememberTheAir** [comment]
@TME97 sorry for the late answer.
As @SaeedRahmani66 said, please check if the privacy settings of your bot are on "_disabled_".
Anyway, this shouldn't affect the private chat with the bot.

Can you give us more informations? Are the received commands printed in the console?

**Comment by TME97** [comment]
@remembertheair:

Bot is now responding, but just in the channel I configurated in the
Log = {
...
}
Section in config file

**Comment by RememberTheAir** [comment]
@TME97 what do you see from the terminal? Do received commands get prited?

**Comment by RememberTheAir** [comment]
I guess I can close this...?

**Comment by alirezamirsepassy** [comment]
Yep I receive "Cron..."
What's the problem?

**Comment by RememberTheAir** [comment]
@alirezamirsepassy the bot is telling you it's running a cronjob. Cronjobs are executed hourly

**Comment by RememberTheAir** [comment]
@dfg260 the timezone of the system where you're running the bot is different from the one used by the API
