### ISSUE TITLE
Change bot language

### ISSUE THREAD

**Issue by barreeeiroo** [RememberTheAir/GroupButler#185]
How to change bot language for a group?
Because I'm trying to execute the command /lang, I select Spanish but nothing happens

**Comment by RememberTheAir** [comment]
Spanish is one of the available languages, but most of the translated strings are outdated.

The bot automatically ignores outdated strings and replaces them with the original English translation.

**Comment by barreeeiroo** [comment]
Oh, okey, thank you

I will try to translate it if I have time
