### ISSUE TITLE
Issue with Multipurpose Plugins

### ISSUE THREAD

**Issue by Santagain** [RememberTheAir/GroupButler#188]
hello all i listed my custom plugins in config.lua in line containing

multipurpose_plugins = {
 'example.lua',
}

and add the files to folder plugins/multipurpose/
but the bot don't load the plugins, 
if i put the plugins on the main folder (plugins) and add to 

plugins = {
 'example.lua',
}

 and start bot, i receive the message with not found error

**Comment by peyman2afm** [comment]
@Santagain Hi.
Put your plugin on "/plugins" and then change the config.lua like this...
```bash
plugins = {
'example',
}
```
Don't use ".lua" in the name of plugin.
I mean don't use this this code:
```bash
plugins = {
'example.lua',
}
```

**Comment by Santagain** [comment]
oh  thanks so much, sorry
