### ISSUE TITLE
spam and mute

### ISSUE THREAD

**Issue by mohscorpion** [RememberTheAir/GroupButler#192]
hi
is there a way to implement these features:
1- mute: disable posting anything into group by users 
2- remove posts containing some keywords ?
thanks for your nice work

**Comment by mymedia2** [comment]
1. Enable silent mode in settings menu
2. Group Butler cannot delete messages

**Comment by mohscorpion** [comment]
thanks for your help.
is there anyway to delete messages?

**Comment by NotAFile** [comment]
No, bots can not delete messages.

**Comment by mohscorpion** [comment]
i know that , but maybe we can log in as a normal user

**Comment by RememberTheAir** [comment]
Group Butler doesn't make use of companion accounts
