### ISSUE TITLE
Multipurpose Plugins

### ISSUE THREAD

**Issue by Santagain** [RememberTheAir/GroupButler#193]
how i can activate the multipurpose plugins ?
i set the following line:

```
	multipurpose_plugins = {
	'test',
	},
```
and create and folder nammed "multipurpose" inside the plugins folder and upload the plugin "test" to inside, but i start the bot but nothing happens

**Comment by RememberTheAir** [comment]
That multipurpose thing was abandoned some time ago, but I've forget to remove that table from config.lua 

You can just add your multipurpose plugins to the standard plugins table

**Comment by Santagain** [comment]
kay, thanks, it's what I'm doing right now :)
