### ISSUE TITLE
Group Butler Doesn't work

### ISSUE THREAD

**Issue by c311at** [RememberTheAir/GroupButler#200]
Group Butler Doesn't work

**Comment by Benjarobbi** [comment]
you're funny. Use the @GroupButler_bot on Telegram or @GBReborn_bot. 

You're providing no error logs etc.

**Comment by Benjarobbi** [comment]
@RememberTheAir close it ;-)

**Comment by RememberTheAir** [comment]
@Benjarobbi I think he was talking about the "official" bot on Telegram

Btw @c311at  you can report problems or issues in our [Telegram group](https://t.me/gbgroups)

**Comment by Benjarobbi** [comment]
Oh, why does he post it then on github. Huh?
