### ISSUE TITLE
Tempban does not auto invite after ban

### ISSUE THREAD

**Issue by LlamaManGuy** [RememberTheAir/GroupButler#207]
After a tempban shouldn't the user be reinvited to the group?

**Comment by NotAFile** [comment]
@LlamaManGuy Thanks for your Request! However, the Bot API does not currently allow bots to add or invite users to groups.

**Comment by LlamaManGuy** [comment]
Well that would be an issue, thanks for the response. Peg this as a request for sure, people that are tempbanned usually think they're gone for good.

**Comment by NotAFile** [comment]
@LlamaManGuy This is true, we can't do it in the way you suggested though :/

A workaround would be the bot attempting to notify users privately when they get unbanned. That seems worth implementing

**Comment by LlamaManGuy** [comment]
@NotAFile That would be just as useful for sure. Thanks for the quick response m8.

**Comment by RememberTheAir** [comment]
@NotAFile @LlamaManGuy the bot [already notifies](https://github.com/RememberTheAir/GroupButler/blob/master/plugins/banhammer.lua#L45) user and group when the ban ends

**Comment by NotAFile** [comment]
@RememberTheAir I wonder if /close works
