### ISSUE TITLE
Problem with new version

### ISSUE THREAD

**Issue by peyman2afm** [RememberTheAir/GroupButler#228]
Hello guys.
I cloned new version of group butler. Then I created `.env`.
Now I want launch bot, but I can't!
Error:
```
lua: /usr/local/share/lua/5.2/redis.lua:380: redis error: ERR invalid DB index
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.2/redis.lua:802: in function </usr/local/share/lua/5.2/redis.lua:801>
        (...tail calls...)
        /usr/local/share/lua/5.2/redis.lua:380: in function 'select'
        ./lua/bot.lua:15: in function 'bot_init'
        ./lua/bot.lua:369: in main chunk
        [C]: in function 'require'
        ./polling.lua:4: in main chunk
        [C]: in ?
```
This is text of line 15 in bot.lua:
```lua
db:select(config.redis.db) --select the redis db
```

What's the problem?

**Comment by yangm97** [comment]
Did you set `$REDIS_DB` to something other than an int in the range of 0 to 16? If so that’s your problem.

**Comment by RememberTheAir** [comment]
@peyman2afm would be useful if you phastebin.com your `.env` file here (with a fake/obscured token obv)

**Comment by peyman2afm** [comment]
@RememberTheAir [Here you can see my .env file](https://hastebin.com/sigomatino.ini)
![Photo](http://uupload.ir/files/kqmu_bandicam_2017-08-05_00-16-56-792.jpg)
Is the place of .env file true?

**Comment by RememberTheAir** [comment]
@peyman2afm what if you change 0 to another number <= 16

**Comment by yangm97** [comment]
If you really want to use index 0 you don’t need to set`$REDIS_DB` at all though.

**Comment by peyman2afm** [comment]
@yangm97 @RememberTheAir Thank you :)
Now it's working successfully.

**Comment by RememberTheAir** [comment]
Did you understand what was causing that error?

**Comment by peyman2afm** [comment]
Yes! The number should not be 0.
I changed the number `REDIS_DB` to 1 and it's working good.
