### ISSUE TITLE
Getting this error after cloning beta branch

### ISSUE THREAD

**Issue by reyasmohammed** [RememberTheAir/GroupButler#229]
I have followed the steps as mentioned in the Readme
Then added .env file with token, my user id etc.

but when I execute via putty ->  ./launch.sh
it gives me the following error.

`lua: [CURL-EASY][URL_MALFORMAT] URL using bad/illegal format or missing URL (3)`

I am running this on a remote server, so I have done all steps via putty.exe.

Earlier I have tried with the master branch, but got a different error.

I have tried printing the url in performrequest method, and the url seems to be fine (with getMe). That url is accessible from my browser too. Is there any port to be opened ? or any log which can give more info about error.

**Comment by RememberTheAir** [comment]
Probably caused by line endings, if you wrote your `.env` file from windows. 

Many texct editors have an option to convert windows line ending to unix line endings

**Comment by reyasmohammed** [comment]
That was perfect, I didnt think that could be the issue.

Thanks for clearing my issue.
