### ISSUE TITLE
网络挂接-webhook 

### ISSUE THREAD

**Issue by sang-shiBu** [RememberTheAir/GroupButler#230]
hello thank to your nice work.
are you want add webhook option to GroupButler?
telegram advanced robots support webhook, time has come to add this feature?
一个大的变化.

**Comment by Synk0** [comment]
Hello, Take a look at it: https://github.com/RememberTheAir/GroupButler/pull/225

**Comment by sang-shiBu** [comment]
@Synk0  i test it but dont work to me as well.
also most codes changed and very complex.
i talk about Simple 结构简单 code like GroupButler codes.

**Comment by sang-shiBu** [comment]
@RememberTheAir want to add webhook with Simple codes?

**Comment by RememberTheAir** [comment]
@sang-shiBu that's the easier way

**Comment by yangm97** [comment]
@sang-shiBu

**Comment by yangm97** [comment]
How’s that complex if that PR is WIP and I haven’t even started adding webhooks _per se_? 🤔

**Comment by sang-shiBu** [comment]
@yangm97 thank to your work, but i test it and receive some error(i test it in my server. Not webhook)
error log is:
_You must export $TG_TOKEN with your Telegram Bot API token_
i set my token in config.lua but Receive this error.

webhook:
also nothing help about how setup webhook in your [pull](https://github.com/RememberTheAir/GroupButler/pull/225) on READ.ME file.

**Comment by yangm97** [comment]
@sang-shiBu This error is not related to the webhook PR. Config has moved from config.lua to environment variables, and it's explained explained how to set these variables on the README. 

I suggest you clone the beta branch and read the README carefully.

Regarding webhook mode not being documented on the PR, it's because it's a WIP (Work In Progress). Since documentation is the last step, you'll have to wait until the PR is finished.

**Comment by sang-shiBu** [comment]
@yangm97 i told, not test webhook.
give me your beta work branch  README file link.
thank you.

**Comment by yangm97** [comment]
@sang-shiBu https://github.com/RememberTheAir/GroupButler/tree/beta

**Comment by sang-shiBu** [comment]
@yangm97 and about webhook, you say we should wait for PR is finish?
so this branch webhook not work yet?

**Comment by yangm97** [comment]
@sang-shiBu Yes

**Comment by sang-shiBu** [comment]
hum.
We arrived at the first point.
add webhook option to GroupButler!
ok we will waiting for this.
