### ISSUE TITLE
Problem with default permissions.

### ISSUE THREAD

**Issue by peyman2afm** [RememberTheAir/GroupButler#231]
I have problem with **default permissions!**
When someone is restrict, he can left the group and rejoin the group. Then GroupButler **change the permissions** of user

_Edit: when an user joins, permissions are changed to the default ones set from the default permissions menu, thus further restrictions  set when the user was a member are lifted when he joins back._

**Comment by RememberTheAir** [comment]
That's a serious bug, thanks for reporting it
