### ISSUE TITLE
[Feature Request] Remove spam message

### ISSUE THREAD

**Issue by mofidhost** [RememberTheAir/GroupButler#240]
When the bot automatically ban someone is publishing other group link or spamming, the message still there... It's a good idea to remove it.

*Now Bots Can Delete Messages !

**Comment by RememberTheAir** [comment]
Deleting messages containing t.me links is already possible using [this mirror](https://t.me/gbreborn_bot) of Group Butler, which is based on the `beta` branch of this repository. One day the blue normal Group Butler will get this function too

**Comment by RememberTheAir** [comment]
@RememberTheAir maybe it works just with other comments
