### ISSUE TITLE
problem after launch

### ISSUE THREAD

**Issue by smhhf** [RememberTheAir/GroupButler#244]
how should i solve this problem?
```
lua: ./lua/languages.lua:20: cannot open file 'locales/tr.po' (No such file or directory)
stack traceback:
        [C]: in function 'lines'
        ./lua/languages.lua:20: in function 'parse'
        ./lua/languages.lua:70: in function 'init'
        ./lua/languages.lua:80: in main chunk
        [C]: in function 'require'
        ./lua/bot.lua:22: in function 'bot_init'
        ./lua/bot.lua:376: in main chunk
        [C]: in function 'require'
        polling.lua:2: in main chunk
        [C]: in ?
```

**Comment by Qwerty-Space** [comment]
@smhhf Looks like it's missing the translation file.  Can you check that it it exists?

**Comment by smhhf** [comment]
> @Qwerty-Space yes all of translation files exist  but, i face another different error appear when i send ./launch.sh ...
lua: [CURL-EASY][URL_MALFORMAT] URL using bad/illegal format or missing URL (3)
what should i do ?

**Comment by RememberTheAir** [comment]
@smhhf your `.env` is using windows line endings. Most of the text editors out there have an option to convert them to the unix `\n`

**Comment by smhhf** [comment]
@RememberTheAir I really appreciate your help , and it was exactly what you said.

**Comment by giuseppeM99** [comment]
About the CRLF problem, is better to remove the `\r` char at the end of the string while loading the env into lua using `string.gsub`

**Comment by NotAFile** [comment]
@giuseppeM99 Yes, could you open a new issue?

**Comment by yangm97** [comment]
@giuseppeM99 I think it would be better if launch.sh converted the file before using, instead of adding a workaround to the code

**Comment by giuseppeM99** [comment]
@yangm97 also this
@NotAFile Ok, i'll open a new issue for this
