### ISSUE TITLE
To whitelist a subdomain/regex

### ISSUE THREAD

**Issue by firesofmay** [RememberTheAir/GroupButler#246]
Hi,

Is it possible to say whitelist a subdomain/regex?
For example `https://blog.project.com/*` instead of whitelisting every new blog post?

Thanks!

**Comment by RememberTheAir** [comment]
You can just whitelist `https://blog.project.com/` to ignore all the links from that blog

Sorry for the late answer

**Comment by firesofmay** [comment]
@RememberTheAir Thanks for replying. So if I want to whitelist say https://medium.com/comanyname/* by whitelisting https://medium.com/comanyname/ it will work for all blog posts under that company?
