### ISSUE TITLE
Auto deleting other links except telegram.me ones?

### ISSUE THREAD

**Issue by NinjaTurtle007** [RememberTheAir/GroupButler#268]
I see option to delete only telegram.me links?
What about all kinds of links? Is there a way to make it delete ANY link posted in the group BUT the ones in a whitelist?

**Comment by Qwerty-Space** [comment]
Yes.  There's a white list option.
See `/help` > Admin Commands > Links whitelist

**Comment by seth-rah** [comment]
Out of curiosity, is there a link blacklist?

Bots are flooding tinyurl links these days.
