### ISSUE TITLE
Old update skipped

### ISSUE THREAD

**Issue by seeavosh** [RememberTheAir/GroupButler#270]
Hi 

after installation, I get this message and bot does not work. 
This is where shows the message: 
--do not process messages from normal groups 
if msg.date < os.time(os.date("!*t")) - 7 then print('Old update skipped') 

It is not normal group, can you let me know what is problem?

**Comment by yangm97** [comment]
@seeavosh try changing 7 into something bigger, like 15

**Comment by NotAFile** [comment]
Please make sure the time your server is set to is accurate.

Closing for duplicate.

**Comment by seeavosh** [comment]
Thanks for answers. I just removed the IF condition and it started to work, I will check your solutions too.
On another topic, does the bot filter words too? for example, if someone sending the bad words and I want to filter it so after they sent it, it delete the message and word them?

Thank you

**Comment by NotAFile** [comment]
no, gb does not do that
