### ISSUE TITLE
How to run GroupButler

### ISSUE THREAD

**Issue by ranrinc** [RememberTheAir/GroupButler#271]
I'm able to run ./launch.sh without a problem and GroupButler is running in the background.
However if I close my SSH windows GroupButler get killed... Is there away to run it in the background? Help?

**Comment by yangm97** [comment]
@ranrinc use tmux or screen

**Comment by NotAFile** [comment]
tmux and is a good temporary measure, but they should not be used for permanently running your bot. 
They don't start the program on boot, collect logs or restart your process if it fails.

Instead, you should look into using a systemd service file or docker.

Closing as unrelated to groupbutler

**Comment by ranrinc** [comment]
@NotAFile any guide in making systemd service?
