### ISSUE TITLE
 [CURL-EASY][URL_MALFORMAT] URL using bad/illegal format or missing URL (3)

### ISSUE THREAD

**Issue by codingsett** [RememberTheAir/GroupButler#274]
I followed the exact procedures and this what i get when  i try to run the bot

` [CURL-EASY][URL_MALFORMAT] URL using bad/illegal format or missing URL (3)`

why does this happen and what is the fix to this

**Comment by NotAFile** [comment]
I guess this is related to something in your configuration being invalid? It doesn't happen for anyone else, either way.

**Comment by RememberTheAir** [comment]
Duplicate of #229 - there's a solution there
