### ISSUE TITLE
Change in spam detection

### ISSUE THREAD

**Issue by annoying-dog** [RememberTheAir/GroupButler#28]
Could you please make it so the part of your bot responsible for spam detection wouldn't detect forwarded messages? Because in my group people forward a lot of messages and get kicked after this.

**Comment by kamikazechaser** [comment]
Hmm....It is very possible to implement this.

**Comment by RememberTheAir** [comment]
Poasible, but I don't know if add it.
It should have its own enable/disable menu.

Something like this could be added if one day an exceptions system for the antispam will be added

**Comment by jarriztg** [comment]
**Funtion**
result > Message > forward_from_chat
https://core.telegram.org/bots/api#message

if forward_chat then
   api.kick.chat.member
end
