### ISSUE TITLE
Bot failed and had to restart itself

### ISSUE THREAD

**Issue by seth-rah** [RememberTheAir/GroupButler#281]
### Steps to reproduce
1.  No steps available sadly, happened while I was asleep.

### Expected behaviour

Not getting an invalid token, and continue to run gracefully

### Actual behaviour

Both my bots seemed to have restarted within 20 minutes of one another during the 01:00 UTC hour.

Specific times here: 

**Bot 1**

On Monday, 26 February 2018, At 01:48:29

**Bot 2**

On Monday, 26 February 2018, At 01:22:47

```lua
groupbutler_1  | Cron...
groupbutler_1  | lua: ./lua/methods.lua:40: Expected value but found invalid token at character 1
groupbutler_1  | stack traceback:
groupbutler_1  |        [C]: in function 'decode'
groupbutler_1  |        ./lua/methods.lua:40: in function <./lua/methods.lua:38>
groupbutler_1  |        (...tail calls...)
groupbutler_1  |        polling.lua:39: in main chunk
groupbutler_1  |        [C]: in ?
groupbutler_1  |
groupbutler_1  | BOT RUNNING:   [@cuteButlerBot] [CuteButler] [478056212]
groupbutler_1  |
groupbutler_1  | Cron...
```

**Operating system:** 

Ubuntu - Docker

Running the latest commit

### Additional information

The bot has been running for about 4 days now, so it has not had this issue before. Not sure if there are different cron jobs set up on the bot, and one of them possibly being problematic.

**Comment by Qwerty-Space** [comment]
@seth-rah That's likely down to Telegram changing something in the API. It happens quite often.

**Comment by seth-rah** [comment]
Hmm

That's interesting because I have 2 bots that both died at different times

The one bot died 4 times while the other was completely fine, both had the same messages in the logs when failing.

![image](https://user-images.githubusercontent.com/2222634/36731362-2c9828ee-1bd3-11e8-891c-6a79316d4c3a.png)

![image](https://user-images.githubusercontent.com/2222634/36731376-395bff56-1bd3-11e8-948c-6411ac1f068d.png)

**Comment by NotAFile** [comment]
Yep, that's just what happens. Sometimes the API returns an invalid response. And if that happens, it is, IMO, much better for the bot to just restart instead of possibly doing something wrong. If you have the bot set up to automatically restart, this shouldn't be much of an issue.

If there are any frequent crashes, it makes sense to fix those, though.

**Comment by seth-rah** [comment]
Righto, will close this one in the meantime unless it becomes a big problem, which I doubt.
