### ISSUE TITLE
What does Telegram have against your robot?

### ISSUE THREAD

**Issue by mmmTelegram** [RememberTheAir/GroupButler#282]
lua: ./lua/methods.lua:40: Expected value but found invalid token at character 1
stack traceback:
        [C]: in function 'decode'
        ./lua/methods.lua:40: in function 'sendRequest'
        ./lua/methods.lua:320: in function <./lua/methods.lua:295>
        (...tail calls...)
        ./polling.lua:28: in function 'init'
        ./polling.lua:35: in main chunk
        [C]: in ?

**Comment by seth-rah** [comment]
This issue might be a duplicate #281 

Also Telegram is currently down in the Europe and MENA regions

https://twitter.com/telegram/status/970595224065069057

**Comment by NotAFile** [comment]
yep. Not really a lot we can do if telegram sends invalid responses.
