### ISSUE TITLE
If I do 'git pull' the settings are not repeated

### ISSUE THREAD

**Issue by mmmTelegram** [RememberTheAir/GroupButler#283]
I am in the old version 4.2.0
https://github.com/RememberTheAir/GroupButler/tree/4e9afda52f39f398c4f9c73bd2b9f051810a81b0
Before the update I do 'sudo service redis-server stop' and it still does not help

**Comment by NotAFile** [comment]
Could you give more details? I'm not sure what you mean.

**Comment by seth-rah** [comment]
I think his database lost its data on a down and up. His database might not be set for production.

**Comment by mmmTelegram** [comment]
I want to upgrade it to beta. But he does not recognize the settings. Once I put it back to the old version everything goes back to normal

**Comment by mmmTelegram** [comment]
I'm talking about a dump.rdb file where all the settings are saved

**Comment by NotAFile** [comment]
what settings specifically are not carried over?

**Comment by mmmTelegram** [comment]
I'm talking about everything

**Comment by Qwerty-Space** [comment]
@mmmTelegram I suggest you make sure that the config file is set to the correct database.

**Comment by NotAFile** [comment]
@mmmTelegram  Sorry, that's really not helpful. There are a number of things that could be considered "settings".

 * user data, stored in redis
 * the contents of the config.lua file
 * the environment variables used to set the bot token

**Comment by mmmTelegram** [comment]
I say everything because I have another bot on the server. And he is beta. But when I want to update the old it gets all the settings of my second bot.

**Comment by NotAFile** [comment]
Yes, if you use the same database ID for two bots they will read and write to the same database and have identical settings. That's just how things work. If you want different settings, you will want to change the database ID.

**Comment by mmmTelegram** [comment]
Where is the ID?

**Comment by NotAFile** [comment]
This is listed in the README.
