### ISSUE TITLE
Allow changing the prefix for #extra commands

### ISSUE THREAD

**Issue by c7oud** [RememberTheAir/GroupButler#287]
Can I change the prefix for #extra commands to “/“ ?

**Comment by NotAFile** [comment]
@c7oud They should work by default

**Comment by c7oud** [comment]
I would like to be able, that the extra commands prefix isnt `#`. Instead I would like to use `/`.

I tried already the command `/extra [/trigger] [reply]` but just `/extra [#trigger] [reply]` is working

**Comment by NotAFile** [comment]
Oh, for #extra commands. Yes, that's intentional. I'm not sure why you would want that, but it's been requested before.

**Comment by c7oud** [comment]
Telegram commands are usually build on the `/` prefix rather than a hashtag. So am I somehow able to replace the prefix or is this at the current time being not possible?

**Comment by NotAFile** [comment]
This is currently not possible, no. Extra commands and real commands are internally very different.

**Comment by c7oud** [comment]
Ok, no problem. Thanks for calcifying.
