### ISSUE TITLE
stupid bugs

### ISSUE THREAD

**Issue by BH-YAGHI** [RememberTheAir/GroupButler#38]
1- bot owner or admins can block Themselves !
2- admins can block bot owner!
and cant unblock they, unless Other admins or owner unblock blocked admins.

**Comment by RememberTheAir** [comment]
You can still unblock by querying the redis db via command line

**Comment by BH-YAGHI** [comment]
how?

**Comment by kamikazechaser** [comment]
i blocked myself once. change owner id and unblock.

**Comment by BH-YAGHI** [comment]
@kamikazechaser stupid
i means is Should not bot block owner or admins.
not way for solve ***how can unblock admins or owner !***

**Comment by BH-YAGHI** [comment]
**fix this bugs is next update**
i close issue.

**Comment by RememberTheAir** [comment]
Lel I won't spend time on this "bug"
