### ISSUE TITLE
i can´t unblockme :c

### ISSUE THREAD

**Issue by eucalipto1** [RememberTheAir/GroupButler#4]
the pattern "/unblock" isn't running. what file must i delete to unblockme? :c

**Comment by RememberTheAir** [comment]
What does "unblock me" means?

**Comment by eucalipto1** [comment]
nothing,,, can i add multiple admins?

**Comment by RememberTheAir** [comment]
Not at the moment, I'm sorry

**Comment by eucalipto1** [comment]
:c ok thanks

**Comment by RememberTheAir** [comment]
Now you can
