### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by mr-attacker** [RememberTheAir/GroupButler#47]
hi when i update to v4 bot dont answer me commands so i can get use /restore

**Comment by RememberTheAir** [comment]
@mr-attacker Any error in the console?

**Comment by mr-attacker** [comment]
i dont know what this error. but bot receiveall msg in terminal but dont answer

**Comment by mr-attacker** [comment]
i think my old data(redis) dont get me i use new version

**Comment by mr-attacker** [comment]
how can fix ?

**Comment by RememberTheAir** [comment]
Uhm I doubt it
With this informations is hard to help you

- Have you changed the api key in config.lua?
- Try to print(text) in the api.sendMessage function, in methods.lua
And see what happens. If you reach this function, messages should be delivered

**Comment by mr-attacker** [comment]
Have you changed the api key in config.lua? bot send me to pv **Bot started!**
but dont answer me commands ( so api key and ID is true setted)

Try to print(text) in the api.sendMessage function, in methods.lua And see what happens. If you reach this function, messages should be delivered
