### ISSUE TITLE
400 [Error : 400 : Bad Request: chat not found]

### ISSUE THREAD

**Issue by banghasan** [RememberTheAir/GroupButler#5]
after edit config, Starting bot and get :

**[Error : 400 : Bad Request: chat not found]**

what wrong?

**Comment by RememberTheAir** [comment]
Wow uhm.... With every message?

**Comment by banghasan** [comment]
oh i know..

it is because are processing old messages and i must /start before to bot

**Comment by RememberTheAir** [comment]
Ah, good to know!
