### ISSUE TITLE
Bot not working on telegram

### ISSUE THREAD

**Issue by N30Exca** [RememberTheAir/GroupButler#51]
From a few day the bot stopper working and dont't return any answer at any Command not Even /help

**Comment by kkraku** [comment]
Yep, can notice this too. Added it to a new group and it isn't responding.

**Comment by kamikazechaser** [comment]
There are several bots. tell us the username of the bot.

**Comment by N30Exca** [comment]
I have issue with group butler sorry for not mentono what bot it was

**Comment by kamikazechaser** [comment]
Use @gbreborn_bot

**Comment by N30Exca** [comment]
not even this work even tested with a fresh new group

**Comment by kamikazechaser** [comment]
It works

**Comment by kamikazechaser** [comment]
Or you can use @gbreborn_bot, @gbfriendbot, @groupthorbot

**Comment by RememberTheAir** [comment]
@N30Exca can you contact me on telegram? @baconnn

**Comment by RememberTheAir** [comment]
Should be solved
