### ISSUE TITLE
isblocked is not work

### ISSUE THREAD

**Issue by usaspk** [RememberTheAir/GroupButler#52]
isblocked commands dont work. are you test it and working without error?

**Comment by RememberTheAir** [comment]
To be honest I don't know if it will work with the latest changes. I need to test it again

**Comment by usaspk** [comment]
**attempt to call global 'is_blocked' (a nil value)**
so dont work at  latest changes. :(

**Comment by usaspk** [comment]
@RememberTheAir  how can solve *No users saved, no broadcast* error? i cant send pm (bc) to my bot members!

**Comment by kamikazechaser** [comment]
use ```/astats``` command and post the results here
