### ISSUE TITLE
Question about flood control

### ISSUE THREAD

**Issue by Kondra007** [RememberTheAir/GroupButler#7]
Hello!   
There's a problem, with spammers and I want to consult you.

So one person uses many (200+ account) to enter public group, send one message and leave (and repeats it many times). Will flood control react if 5 people will send one message each within X seconds.

Feature request 1: Enable flood control for all users at once, so if 10 people write 10 messages (1 for each) within X seconds, bot starts kicking.

Feature request 2: If users joins channel, delete all messages from him for an hour (quarantine time)

**Comment by RememberTheAir** [comment]
Hello,

Unfortunately about point 1, such a feature wil result in a loooooot of people complaining if the bot kicks for flood. trust me, I already receive a lot of complains from people saying the bot is kicking for no reason, when actually they have antiflood enabled and setted to the minimum value.
Altough it could be a nice feature, I don't think it could be a big deal :(

For the second one.... at the moment Telegram apis don't offer a method to delete mnessages (but the bot support told me it will be added soon). So for now I can't do anything about this, sorry

**Comment by Kondra007** [comment]
Since our group was flooded win 6k+ messages from lots of fake users, trust me, it's needed.

And your bot uses CLI, doesn't it? If yes, it's a "real" account and CAN delete messages.

**Comment by RememberTheAir** [comment]
Ah ehm my bot doesn't use tg-cli, it actually uses Telegram Api (you can see the word "bot" under its name)

**Comment by Kondra007** [comment]
Sorry, my fault. I naturally think of all Lua bots as CLI ones.

**Comment by Kondra007** [comment]
But please, think of point 1

**Comment by RememberTheAir** [comment]
Eheh I can understand :)
Anyway (I'll post the screen in the channel too) api bot will be able to delete messages soon, I've asked to te official bot support and they told me this

Anyway, I will consider point 1

**Comment by Kondra007** [comment]
Excuse me, in what channel?

**Comment by RememberTheAir** [comment]
Ah, the channel where I post updates about the bot. you can find it [here](https://telegram.me/GroupButler_ch)

**Comment by RememberTheAir** [comment]
Where is th*
