### ISSUE TITLE
Bot halts after initiating chat with him

### ISSUE THREAD

**Issue by Kondra007** [RememberTheAir/GroupButler#8]
So, I've installed your bot, added it to supergroup, wrote "help", he said "Write to me first", I didn't do this, pressed "/help" again in supergroup, bot got `Error : 400 : PEER_ID_INVALID` in logs and stopped responding to everybody.

Only after I restarted it, he became working again. Could you confirm this?

**Comment by RememberTheAir** [comment]
Uhm that's a weird behaviour
What if you try with "/init", what happens?

**Comment by Kondra007** [comment]
Nothing happens. Cheked it again, here's test case:

1) Add bot to supegroup
2) Write "/help". Bot will say "Please write to me first"
Every time you press "/help" he'll say this.
3) Open dialogue with bot and press "/start"
4) Return to supergroup and try sending "/help" from anyone. Bot won't respond at all.

**Comment by RememberTheAir** [comment]
Let me simulate this

**Comment by RememberTheAir** [comment]
Uhm I've tried with two different accounts and it's all working here
Are you still facing the issue?

**Comment by Kondra007** [comment]
Could you plese add me to Telegram? telegram.me/groosha

**Comment by Kondra007** [comment]
Solved in private messaging.
