### ISSUE TITLE
can be add banall ?

### ISSUE THREAD

**Issue by BH-YAGHI** [RememberTheAir/GroupButler#9]
i dont see banall user in yout source !
 can add it>?

**Comment by RememberTheAir** [comment]
There is /gban command (never tested)
In banhammer.lua

**Comment by RememberTheAir** [comment]
And, /gban is not working now. I'll fix soon

**Comment by BH-YAGHI** [comment]
so ok..

boy your ApI bot how Re launch?

**Comment by RememberTheAir** [comment]
@BH-YAGHI Run "/init" command

**Comment by BH-YAGHI** [comment]
For what ? What is this command ?

**Comment by BH-YAGHI** [comment]
Bot reloaded! :)

So you fix this function ?

May most git pull ? Or don't need !?

**Comment by RememberTheAir** [comment]
It's not fixed yet
Wait for the next update :)

**Comment by BH-YAGHI** [comment]
Ok
