### ISSUE TITLE
Feature request: Automatic delete

### ISSUE THREAD

**Issue by Mistero5050** [RememberTheAir/GroupButler#96]
I don't know if this is already in action so I'll ask for it anyway.

1) If a user spams, shouldn't the flood messages be deleted by default? Does the bot do it now?
2) If a user share a restricted media (set to not be sent by the /media command), does the bot delete it automatically?

Thanks for your answers and sorry for my bad English

**Comment by RememberTheAir** [comment]
The bot api doesn't  allow to delete messages yet

**Comment by Mistero5050** [comment]
Ok, thanks. Maybe when it will be released can you do it?

**Comment by Benjarobbi** [comment]
I think he'll implent then something like this.

**Comment by Mistero5050** [comment]
Ok, you can close it then. Thanks
